name = "wisp_basic_auth"
version = "1.0.298"

description = "Basic HTTP Authentication Scheme for Wisp"
licences = ["Apache-2.0"]
repository = { type = "github", user = "devstopfix", repo = "wisp_basic_auth" }
# links = [{ title = "Website", href = "" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
wisp = ">= 2.0.0 and < 3.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
